server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estoque-equipment
    username: postgres
    password: server2022
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        log.non-contextual-creation: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true